export type Language = 'pt' | 'en' | 'fr';

export const APP_VERSION = '0.0.48';

export const changelogData = [
  {
    version: '0.0.48',
    date: new Date().toISOString().split('T')[0],
    changes: {
      pt: [
        'Core: Restaurada a geração de introdução e opções iniciais ao começar uma nova obra.',
        'Core: Alertas de "Ligação Interrompida" agora mostram a causa do erro de conexão.'
      ],
      en: [
        'Core: Restored the generation of introductory text and initial options when starting a new work.',
        'Core: "Connection Interrupted" alerts now display the cause of the connection error.'
      ],
      fr: [
        "Core : Restauration de la génération de l'introduction et des options initiales lors du démarrage d'une nouvelle œuvre.",
        "Core : Les alertes 'Connexion Interrompue' affichent désormais la cause de l'erreur de connexion."
      ]
    }
  },
  {
    version: '0.0.47',
    date: new Date().toISOString().split('T')[0],
    changes: {
      pt: [
        'Estabilidade: Resolvido o "piscar" (flicker) entre ecrãs (Home/Dashboard) ao recarregar a app.',
        'Core: Recuperação robusta de erros caso o sistema de "Gerar Sugestões" falhe na Comunicação com a IA.',
        'Core: Exportação final de PDF agora muito mais rápida e sem causar bloqueios ou desistências na Sinopse.'
      ],
      en: [
        'Stability: Resolved the transition flicker between screens (Home/Dashboard) when refreshing the app.',
        'Core: Robust error recovery if the "Generate Suggestions" system fails to communicate with AI.',
        'Core: Final PDF export is now much faster and avoids timeouts during Synopsis creation.'
      ],
      fr: [
        'Stabilité : Résolution du "scintillement" (flicker) entre les écrans au rechargement de l\'application.',
        'Core : Récupération robuste des erreurs en cas d\'échec du système "Générer des suggestions".',
        'Core : L\'exportation PDF finale est maintenant plus rapide et sans délais d\'attente du synopsis.'
      ]
    }
  },
  {
    version: '0.0.46',
    date: new Date().toISOString().split('T')[0],
    changes: {
      pt: [
        'Estabilidade: Corrigido o erro "Connection Interrupted" causado por persistência de modelos depreciados ou inválidos nas chamadas de IA.',
        'Core: Otimização das rotas de tradução e geração de prosa para maior resiliência.'
      ],
      en: [
        'Stability: Fixed "Connection Interrupted" error caused by invalid or deprecated model names in AI calls.',
        'Core: Optimization of translation and prose generation routes for better resilience.'
      ],
      fr: [
        'Stabilité : Correction de l\'erreur "Connection Interrupted" causée par des noms de modèles invalides ou obsolètes.',
        'Core : Optimisation des routes de traduction et de génération de prose.'
      ]
    }
  },
  {
    version: '0.0.45',
    date: new Date().toISOString().split('T')[0],
    changes: {
      pt: [
        'Estabilidade: Corrigido o erro "Connection Interrupted" causado por persistência de modelos depreciados ou inválidos nas chamadas de IA.',
        'Core: Otimização das rotas de tradução e geração de prosa para maior resiliência.'
      ],
      en: [
        'Stability: Fixed "Connection Interrupted" error caused by invalid or deprecated model names in AI calls.',
        'Core: Optimization of translation and prose generation routes for better resilience.'
      ],
      fr: [
        'Stabilité : Correction de l\'erreur "Connection Interrupted" causée par des noms de modèles invalides ou obsolètes.',
        'Core : Optimisation des routes de traduction et de génération de prose.'
      ]
    }
  },
  {
    version: '0.0.44',
    date: new Date().toISOString().split('T')[0],
    changes: {
      pt: [
        'Narrativa: Implementação de Árvore Prosaística (Branching) com IDs únicos por parágrafo.',
        'Visual: Adição de Geração de Imagens dinâmica baseada no contexto e género.',
        'Áudio: Novo Narrador AI (TTS) com vozes PT-PT, ENG e FR.',
        'Interface: Adição de Sidebar de Inventário e Modo Zen para escrita focada.'
      ],
      en: [
        'Narrative: Implementation of Prose Tree (Branching) with unique IDs per paragraph.',
        'Visual: Addition of dynamic Image Generation based on context and genre.',
        'Audio: New AI Narrator (TTS) with PT-PT, ENG, and FR voices.',
        'Interface: Added Inventory Sidebar and Zen Mode for focused writing.'
      ],
      fr: [
        'Narratif : Implémentation de l\'Arbre Narratif (Branching).',
        'Visuel : Ajout de la génération d\'images dynamique.',
        'Audio : Nouveau Narrateur AI (TTS) avec voix PT-PT, ENG et FR.',
        'Interface : Ajout d\'une barre d\'inventaire et du Mode Zen.'
      ]
    }
  },
  {
    version: '0.0.43',
    date: new Date().toISOString().split('T')[0],
    changes: {
      pt: [
        'IA: Geração de títulos criativos automáticos baseados no conceito e personagens da obra.',
        'Modo Espectador: Permite observar sessões Co-Op em tempo real sem ocupar lugar de autor.',
        'UX/UI: Novo modal de "Configuração" no motor de jogo e acesso persistente a sessões ativas no Dashboard.',
        'Lobby: Melhoria na interface de convite com ícone de cópia direto e remoção de botões redundantes.'
      ],
      en: [
        'AI: Automatic generation of creative titles based on the work\'s concept and characters.',
        'Spectator Mode: Allows real-time observation of Co-Op sessions without taking an author spot.',
        'UX/UI: New "Configuration" modal in the game engine and persistent access to active sessions on the Dashboard.',
        'Lobby: Improved invite interface with direct copy icon and removal of redundant buttons.'
      ],
      fr: [
        'IA : Génération automatique de titres créatifs basés sur le concept et les personnages de l\'œuvre.',
        'Mode Spectateur : Permet d\'observer les sessions Co-Op en temps réel sans occuper une place d\'auteur.',
        'UX/UI : Nouveau modal de "Configuration" dans le moteur de jeu et accès persistant aux sessions actives sur le tableau de bord.',
        'Lobby : Amélioration de l\'interface d\'invitation avec icône de copie directe et suppression des boutons redondants.'
      ]
    }
  },
  {
    version: '0.0.42',
    date: '2026-02-24',
    changes: {
      pt: [
        'Arquitetura: Otimização maciça de desempenho dividindo Views num sistema modular (React Router).',
        'State Management: Estado global transferido para Zustand para erradicar recarregados desnecessários da página.',
        'Desenvolvimento: Implementado o ambiente de Testes Unitários com Vitest.',
        'Co-Op Live Session: Resolvido o problema "Connection Interrupted with Editor" que criava turnos bloqueados após sobreposição de vários autores ao mesmo tempo.'
      ],
      en: [
        'Architecture: Massive performance optimization by splitting Views into a modular system (React Router).',
        'State Management: Global state transferred to Zustand to eradicate unnecessary page reloads.',
        'Development: Implemented Unit Test environment with Vitest.',
        'Co-Op Live Session: Resolved the "Connection Interrupted with Editor" issue that created stuck turns after overlapping requests from multiple authors.'
      ],
      fr: [
        'Architecture : Optimisation massive des performances en divisant les vues en un système modulaire (React Router).',
        'Gestion de l\'État : État global transféré vers Zustand pour éradiquer les rechargements de page inutiles.',
        'Développement : Environnement de tests unitaires implémenté avec Vitest.',
        'Session Live Co-Op : Résolution du problème "Connection Interrupted with Editor" causé par les chevauchements de requêtes de plusieurs auteurs simultanément.'
      ]
    }
  },
  {
    version: '0.0.41',
    date: '2024-06-21',
    changes: {
      pt: [
        'UX: Sugestões da IA agora apresentadas numa grelha uniforme e legível, facilitando a escolha da próxima ação.',
        'Melhorias visuais na área de input.'
      ],
      en: [
        'UX: AI suggestions now displayed in a uniform and readable grid, making it easier to choose the next action.',
        'Visual improvements in the input area.'
      ],
      fr: [
        'UX : Suggestions de l\'IA désormais affichées dans une grille uniforme et lisible.',
        'Améliorations visuelles de la zone de saisie.'
      ]
    }
  },
  {
    version: '0.0.40',
    date: '2024-06-20',
    changes: {
      pt: [
        'Biblioteca Global: Botão de tradução agora disponível para todas as obras, permitindo traduzir para o teu idioma preferido independentemente do idioma original.',
        'Correção de estabilidade nas chamadas de IA (Streaming).'
      ],
      en: [
        'Global Library: Translation button now available for all works, allowing translation to your preferred language regardless of the original language.',
        'Stability fix in AI calls (Streaming).'
      ],
      fr: [
        'Bibliothèque Mondiale : Bouton de traduction désormais disponible pour toutes les œuvres.',
        'Correction de stabilité dans les appels IA (Streaming).'
      ]
    }
  },
  {
    version: '0.0.39',
    date: '2024-06-19',
    changes: {
      pt: [
        'UX: Nova "Control Dock" fixa. Todas as ferramentas de autor (Co-Op, Texto, Finais) estão agora numa barra inferior unificada e sempre acessível.',
        'Leitura: Bloqueio de scroll automático durante a escrita da IA. O texto já não "foge" enquanto lês o que está a ser gerado.',
        'Personalização: Controlo de tamanho de letra (A+/A-) com persistência no perfil de utilizador.'
      ],
      en: [
        'UX: New fixed "Control Dock". All author tools (Co-Op, Text, Endings) are now in a unified, always-accessible bottom bar.',
        'Reading: Disabled auto-scroll during AI writing. The text no longer "jumps" away while you are reading generated content.',
        'Customization: Font size control (A+/A-) with user profile persistence.'
      ],
      fr: [
        'UX : Nouveau "Control Dock" fixe. Tous les outils d\'auteur sont désormais dans une barre inférieure unifiée et toujours accessible.',
        'Lecture : Désactivation du défilement automatique pendant l\'écriture de l\'IA.',
        'Personnalisation : Contrôle de la taille de la police (A+/A-) avec persistance dans le profil utilisateur.'
      ]
    }
  },
  {
    version: '0.0.38',
    date: '2024-06-18',
    changes: {
      pt: [
        'Co-Op Strict Mode: Implementada regra de "Bloqueio de Autor Consecutivo". Se foste o último a escrever, o sistema impede-te de jogar novamente até que outro participante o faça.',
        'Cloud Sync: Correção crítica na persistência de dados (participants & config) durante atualizações de turno.'
      ],
      en: [
        'Co-Op Strict Mode: Implemented "Consecutive Author Block". If you were the last to write, the system prevents you from playing again until another participant does.',
        'Cloud Sync: Critical fix in data persistence (participants & config) during turn updates.'
      ],
      fr: [
        'Co-Op Strict Mode : Mise en place du "Blocage d\'Auteur Consécutif".',
        'Cloud Sync : Correction critique de la persistance des données lors des mises à jour de tour.'
      ]
    }
  },
  // ... existing changelogs ...
  {
    version: '0.0.01',
    date: '2024-05-23',
    changes: {
      pt: [
        'Implementação do Sistema de Registo de Atualizações (Changelog).',
        'Novo botão "Novidades" na Dashboard com notificação de atualização.',
        'Correção do redirecionamento após confirmação de e-mail (Auth Fix).',
        'Início do versionamento semântico.'
      ],
      en: [
        'Implemented Changelog System.',
        'New "What\'s New" button on Dashboard with update notification.',
        'Fixed email confirmation redirect issue (Auth Fix).',
        'Started semantic versioning.'
      ],
      fr: [
        'Mise en œuvre du système de journal des modifications.',
        'Nouveau bouton "Nouveautés" sur le tableau de bord avec notification.',
        'Correction de la redirection de confirmation par e-mail.',
        'Début du versionnage sémantique.'
      ]
    }
  }
];

export const translations = {
  pt: {
    // ... existing keys ...
    title: 'IA-Ventura',
    tagline: 'O teu Estúdio de Escrita Colaborativa com Inteligência Artificial.',
    textSize: 'Tamanho do Texto',
    tools: 'Ferramentas',

    // ... existing keys ...
    renovateCode: 'Renovar Código',
    confirmRenovate: 'Tens a certeza? O código atual deixará de funcionar e todos os participantes terão de entrar novamente com o novo código.',
    codeRenovated: 'Novo código gerado com sucesso!',
    nudge: 'Chamar',
    nudgeSent: 'Notificação enviada por e-mail!',
    translate: 'Traduzir Obra',
    translateDesc: (lang: string) => `Traduzir esta obra para ${lang.toUpperCase()}`,
    showOriginal: 'Ver Original',
    translating: 'A traduzir obra...',
    managePlayers: 'Gerir Participantes',
    kick: 'Expulsar',
    confirmKick: 'Tens a certeza que queres expulsar este autor?',
    kickedMessage: 'Foste removido desta sessão pelo anfitrião.',
    selectModeTitle: 'Modo de Escrita',
    modeSolo: 'Autor a Solo',
    modeSoloDesc: 'Escreve ao teu ritmo com a ajuda da IA.',
    modeCoop: 'Grupo Co-Op',
    modeCoopDesc: 'Cria uma sala, convida amigos e escrevam juntos.',
    modeSoloTooltip: 'Cria uma obra clássica ao teu próprio ritmo. O Editor IA estará ao teu lado para te ajudar a estruturar a narrativa.',
    modeCoopTooltip: 'Convida amigos para a sala. Vocês escrevem em turnos sincronizados, enquanto a IA atua como Game Master.',
    lobbyTitle: 'Sala de Espera',
    waitingForPlayers: 'A aguardar participantes...',
    startGame: 'Iniciar Configuração',
    host: 'Anfitrião',
    setupWait: 'O Anfitrião está a configurar a história...',
    playAsYourself: 'Interpretar a Si Mesmo (RPG Mode)',
    playAsYourselfDesc: 'Cada autor recebe uma ficha de personagem para preencher e controlar.',
    assignedToYou: 'Atribuído a Ti',
    lockedBy: 'Controlado por',
    landingTitle: 'Dá vida à tua próxima obra literária.',
    landingDesc: 'A plataforma definitiva para autores modernos. Combina a tua imaginação com o poder da IA para criar, editar e publicar obras literárias de qualidade profissional.',
    featuresTitle: 'O que podes fazer no Estúdio:',
    feature1Title: 'Planeamento Criativo',
    feature1Desc: 'Define o género, cria fichas de personagens detalhadas e estabelece a premissa com ajuda da IA.',
    feature2Title: 'Escrita Híbrida & Co-Op',
    feature2Desc: 'Escreve a par com o Editor IA ou convida amigos para sessões de escrita em tempo real.',
    feature3Title: 'Publicação Profissional',
    feature3Desc: 'Transforma o teu rascunho num livro PDF formatado, com sinopse e revisão editorial automática.',
    feature4Title: 'Comunidade Global',
    feature4Desc: 'Lê obras de outros autores, segue os teus favoritos e constrói o teu portefólio literário.',
    login: 'Entrar',
    signup: 'Registar',
    noAccount: 'Ainda não tens conta?',
    haveAccount: 'Já tens conta?',
    logout: 'Sair',
    email: 'E-mail',
    password: 'Palavra-passe',
    confirmPassword: 'Confirmar Palavra-passe',
    passMismatch: 'As palavras-passe não coincidem.',
    username: 'Utilizador',
    createStory: 'Nova Obra',
    drafts: 'Rascunhos',
    draftsSubtitle: 'Trabalhos em curso e rascunhos.',
    coopWorks: 'Obras Co-Op',
    coopWorksSubtitle: 'Sessões cooperativas ativas.',
    cardCoopWorksDesc: 'Acede às tuas sessões de escrita em grupo.',
    privateLibrary: 'Obras Concluídas',
    privateLibrarySubtitle: 'Obras finalizadas e prontas para leitura.',
    publicLibrary: 'Biblioteca Global',
    publicLibrarySubtitle: 'Obras partilhadas pela comunidade de autores.',
    authorsClub: 'Clube de Autores',
    authorsSubtitle: 'Conhece as mentes criativas da plataforma.',
    authorsLoading: 'A carregar perfis de autores...',
    globalLoading: 'A sincronizar biblioteca global...',
    profile: 'Perfil',
    startAdventure: 'Começar a Escrever',
    send: 'Enviar',
    sendWait: 'A aguardar turno de:',
    waitingAI: 'O Editor está a escrever...',
    newTurnReceived: 'Novo turno recebido de um co-autor!',
    noStories: 'Sem obras finalizadas.',
    noDrafts: 'Não tens rascunhos pendentes.',
    searchAuthor: 'Procurar autor...',
    back: 'Voltar',
    next: 'Seguinte',
    devBypass: 'Modo Programador (Bypass)',
    guestLogin: 'Entrar como Convidado',
    guestLoginDesc: 'Continua como Convidado para experimentar todas as funcionalidades. Se quiseres guardar os teus dados, terás de registar uma conta.',
    version: `v${APP_VERSION}`,
    setupTitle: 'Configuração da Obra',
    setupMode: 'Como pretendes iniciar?',
    ownIdea: 'Tenho a Obra definida',
    aiIdea: 'Sugestões de Obra pela IA',
    ideaPlaceholder: 'Descreve a ideia base ou o resumo da tua Obra...',
    charCount: 'Número de personagens',
    genreTitle: 'Género Literário',
    qualityTitle: 'Estilo de Escrita',
    qualityRich: 'Literário (Descritivo)',
    qualityRichDesc: 'Foco na prosa elaborada, introspecção e ambientação rica.',
    qualityDirect: 'Dinâmico (Direto)',
    qualityDirectDesc: 'Foco no ritmo, diálogos fluidos e progressão rápida.',
    charNamesTitle: 'Elenco de Personagens',
    charNamesPlaceholder: 'Ex: Elara Vance',
    charRole: 'Função Narrativa',
    charTrait: 'Perfil Psicológico',
    charTraitPlaceholder: 'Ex: Introvertido, ambicioso, melancólico...',
    charBackstory: 'História Pregressa',
    charBackstoryPlaceholder: 'O que moldou esta personagem antes da história começar?',
    charMotivations: 'Motivations',
    charMotivationsPlaceholder: 'O que a move? Qual o seu maior objetivo?',
    addCharacter: 'Adicionar Personagem',
    removeCharacter: 'Remover',
    charLimit: 'Máximo de 5 personagens atingido.',
    roleProtagonist: 'Protagonista',
    roleAntagonist: 'Antagonista',
    roleSidekick: 'Secundário',
    charLinksTitle: 'Dinâmica do Grupo',
    charLinksPlaceholder: 'Descreve as ligações, segredos ou tensões entre as personagens...',
    mainChar: 'Personagem Central',
    isMainChar: 'Foco Narrativo',
    generateBook: 'Gerar Livro',
    polishingTitle: 'Revisão Editorial',
    polishingDesc: 'O Editor está a ler a obra completa, a criar a sinopse e a gerar opções de títulos. Este processo pode demorar até 1 minuto. Por favor, aguarda...',
    synopsis: 'Sinopse Editorial',
    bookPreview: 'Visualização da Obra',
    downloadPDF: 'Exportar para PDF',
    resumeStory: 'Continuar Escrita',
    backToHome: 'Painel Principal',
    author: 'Autor',
    date: 'Data',
    delete: 'Eliminar',
    resume: 'Retomar',
    readBook: 'Ler Obra',
    confirmDelete: 'Mover para o arquivo?',
    confirmDeletePublic: 'Remover esta obra da Biblioteca Global?',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    publish: 'Publicar',
    publishedSuccess: 'Obra publicada com sucesso!',
    publishError: 'Erro ao publicar.',
    rating: 'Avaliação',
    readOnly: 'Apenas Leitura',
    connectionError: 'Ligação Interrompida com o Editor.',
    connectionDesc: 'Não foi possível contactar o Editor.',
    online: 'Online',
    offline: 'Offline',
    authorsTitle: 'Comunidade Literária',
    works: 'Obras',
    welcomeBack: 'Bem-vindo ao teu Estúdio,',
    exploreFuncs: 'Gere as tuas obras e explora novas ideias.',
    cardCreateDesc: 'Inicia uma nova obra com apoio da IA.',
    cardDraftsDesc: 'Continua a trabalhar nos teus rascunhos.',
    cardLibraryPrivateDesc: 'Acede às tuas obras finalizadas.',
    cardLibraryPublicDesc: 'Lê o que outros autores publicaram.',
    cardAuthorsDesc: 'Vê o perfil de outros escritores.',
    cardArchiveDesc: 'Recupera itens eliminados.',
    makeFriend: 'Seguir Autor',
    isFriend: 'Seguindo',
    viewAuthorWorks: 'Ver Bibliografia',
    privateWorks: 'Obras Concluídas',
    publishedWorks: 'Obras Publicadas',
    authorBooksTitle: 'Bibliografia do Autor',
    noAuthorWorks: 'Este autor ainda não tem obras publicadas.',
    close: 'Fechar',
    notifications: 'Notificações',
    noNotifications: 'Sem notificações.',
    friendNewBook: 'finalizou uma nova obra:',
    markAllRead: 'Lidas',
    archive: 'Arquivo',
    archiveSubtitle: 'Gestão de rascunhos eliminados.',
    restore: 'Restaurar',
    deletePermanent: 'Eliminar Permanente',
    daysRemaining: 'Dias',
    noArchived: 'Arquivo vazio.',
    archiveWarning: 'Os itens no arquivo são eliminados após 30 dias.',
    expiringSoon: 'Expira em breve!',
    deletePermanentlyConfirm: 'Eliminar permanentemente?',
    requestEnding: 'Fechar Capítulo',
    endingPrompt: 'Escreve o desfecho deste arco ou capítulo de forma literária.',
    requestDefinitiveEnding: 'Fim Definitivo',
    definitiveEndingPrompt: 'Cria uma conclusão absoluta para esta obra. Resolve todos os conflitos, oferece um desfecho emocional satisfatório e encerra a história de forma definitiva, sem ganchos ou mistérios pendentes.',
    endingActive: 'Finalização Ativa',
    introGenerating: 'O Editor está a redigir a introdução...',
    endingLockedReason: (needed: number) => `A narrativa ainda requer mais desenvolvimento (Mínimo ${needed} parágrafos).`,
    aiSystemRole: 'Atuas como um "Editor Literário IA" de elite em PT-PT. REGRAS DE OURO: 1. NUNCA respondas a conversas, pedidos de desculpa ou frases do utilizador. O teu output deve ser 100% NARRATIVE. 2. Se o utilizador der uma instrução (ex: "continua", "corrige"), executa-a silenciosamente no texto sem dizer "Ok" ou "Aqui está". 3. Cada fala de personagem deve estar num novo parágrafo com travessão (—). 4. Evita meta-comentários.',
    aiInitialPrompt: (idea: string, style: string, genre: string, chars: string, leader: string, links: string) => `Saudações, Autor. Iniciamos a redação desta obra de ${genre}. CONCEITO: ${idea}. ELENCO: ${chars}. RELAÇÕES: ${links}. Redige o primeiro capítulo focando na imersão e introdução das personagens.`,
    tutorialTitle: 'Manual do Autor',
    tutorialStep1: 'Nova Obra',
    tutorialStep1Desc: 'Inicia uma nova aventura literária. Podes criar a tua história a solo ou convidar amigos para o Modo Co-Op.',
    tutorialStep2: 'Rascunhos',
    tutorialStep2Desc: 'Acede às tuas obras em curso. Nunca percas o fio à meada e retoma a escrita exatamente onde ficaste.',
    tutorialStep3: 'Obras Concluídas',
    tutorialStep3Desc: 'A tua estante pessoal com todas as obras finalizadas. Exporta para PDF, traduz ou publica-as.',
    tutorialStep4: 'Biblioteca Global',
    tutorialStep4Desc: 'Explora o vasto universo de obras publicadas por outros autores. Lê, avalia e deixa-te inspirar.',
    tutorialStep5: 'Clube de Autores',
    tutorialStep5Desc: 'Conhece as mentes criativas da plataforma. Segue os teus autores favoritos e acompanha os seus lançamentos.',
    tutorialStep6: 'Arquivo',
    tutorialStep6Desc: 'Acede a obras e rascunhos que apagaste. Podes restaurá-los se mudares de ideias (itens guardados por 30 dias).',
    coopModalTitle: 'Como funciona o Modo Co-Op?',
    coopStep1: 'Lobby & Convites',
    coopStep1Desc: 'Cria um Lobby e partilha o código ou link com amigos. O anfitrião controla quem entra (e quem sai).',
    coopStep2: 'Setup Colaborativo',
    coopStep2Desc: 'Todos veem as personagens. O Anfitrião define a história, mas todos podem criar o seu próprio herói no modo RPG.',
    coopStep3: 'Sincronização em Tempo Real',
    coopStep3Desc: 'Escrevem à vez. O "cadeado" indica de quem é o turno. A IA mantém a coesão entre todos os autores.',
    coopStep4: 'Modos & Papéis',
    coopStep4Desc: 'No modo "Clássico", todos controlam tudo. No modo "RPG (Interpretar a Si Mesmo)", cada autor controla apenas a sua personagem.',
    genres: {
      fantasy: 'Fantasia',
      high_fantasy: 'Alta Fantasia',
      urban_fantasy: 'Fantasia Urbana',
      scifi: 'Ficção Científica',
      hard_scifi: 'Ficção Científica Hard',
      space_opera: 'Space Opera',
      hist_romance: 'Romance Histórico',
      regency: 'Romance de Época',
      thriller: 'Thriller',
      crime: 'Policial / Crime',
      horror: 'Terror',
      psych_horror: 'Terror Psicológico',
      mystery: 'Mistério',
      noir: 'Noir',
      drama: 'Drama',
      dystopia: 'Distopia',
      adventure: 'Aventura',
      western: 'Western',
      romcom: 'Romance Contemporâneo',
      cyberpunk: 'Cyberpunk',
      steampunk: 'Steampunk',
      magical_realism: 'Realismo Mágico',
      fairy_tale: 'Fábula / Conto de Fadas',
      satire: 'Sátira',
      spy: 'Espionagem',
      mythology: 'Mitologia',
      biography: 'Biografia Ficcional',
      comedy: 'Comédia',
      tragedy: 'Tragédia',
      slice_of_life: 'Slice of Life',
      litrpg: 'LitRPG / Isekai',
      superhero: 'Super-Heróis',
      surprise: 'Surpresa 🎉'
    },
    tutorialIntro: 'Bem-vindo ao IA-Ventura, o teu estúdio de redação assistida.',
    tutorialBtn: 'Entendido',
    authError: 'Erro de acesso.',
    loginSuccess: 'Bem-vindo ao Estúdio!',
    signupSuccess: 'Verifica o teu e-mail para confirmar a conta.',
    fallbackSuggestion1: 'Desenvolver diálogo.',
    fallbackSuggestion2: 'Descrever ambiente.',
    fallbackSuggestion3: 'Explorar pensamento.',
    joinSession: 'Entrar no Modo Co-Op',
    joinSessionDesc: 'Introduz o código para colaboração.',
    enterCode: 'Código da Sessão',
    join: 'Entrar',
    sessionError: 'Sessão não encontrada.',
    liveSync: 'Sincronização Neural',
    inviteCode: 'Código de Convite',
    help: 'Ajuda',
    copy: 'Copiar',
    startLiveSession: 'Modo Cooperativo',
    liveSessionActive: 'CO-OP',
    shareWithCoAuthor: 'Partilha este código com o teu co-autor:',
    syncing: 'A sincronizar (Turno do Co-Autor)...',
    publishToGlobal: 'Publicar na Biblioteca',
    publishing: 'A Analisar Narrativa...',
    alreadyPublished: 'Já publicada',
    acclaim: 'Aclamar',
    votes: 'Aclamações',
    removePublic: 'Privatizar',
    confirmRemovePublic: 'Tens a certeza que queres remover esta obra da Biblioteca Global?',
    removedSuccess: 'Obra removida da biblioteca pública.',
    successTitle: 'Sucesso!',
    goToLogin: 'Ir para Login',
    generatingConcepts: 'A gerar conceitos de Obra...',
    tryAgain: 'Tentar novamente',
    stepCounter: (c: number, t: number) => `Passo ${c} de ${t}`,
    noName: 'Sem Nome',
    guestCoopLock: 'Regista-te para desbloquear o Modo Cooperativo e escrever com amigos.',
    whatsNew: 'Novidades',
    changelogTitle: 'Registo de Atualizações',
    newUpdate: 'Nova Versão!',
    activeSession: 'Sessão Ativa',
    backToLobby: 'Voltar ao Lobby',
    reopenBook: 'Reabrir para Edição',
    reopenWarn: 'A obra voltará aos rascunhos.',
    howItWorks: 'Como funciona?',
    labelName: 'Nome',
    labelRole: 'Função',
    labelTraits: 'Traços & Personalidade',
    turnYourTurn: 'É a tua vez de escrever!',
    turnLocked: 'Modo Espectador',
    turnParticipants: 'Autores na Sessão',
    titleSelection: 'Definir Título da Obra',
    selectTitleDesc: 'O Editor sugeriu 3 títulos para a tua obra. Escolhe um ou escreve o teu próprio.',
    customTitlePlaceholder: 'Escreve o teu título personalizado...',
    orCustom: 'Ou cria o teu título original',
    inviteFriend: 'Convidar Amigo',
    inviteDesc: 'Partilha o link ou envia um e-mail para trazeres um co-autor para esta história.',
    copyLink: 'Copiar Link',
    linkCopied: 'Link Copiado!',
    sendEmail: 'Enviar E-mail',
    shareLink: 'Partilhar Link',
    inviteSubject: 'Convite para escrever no AI-Ventura',
    inviteBody: (code: string, link: string) => `Olá! Junta-te a mim para escrevermos uma história no AI-Ventura.\n\nCódigo da Sessão: ${code}\n\nOu clica diretamente aqui: ${link}`,
    inviteDetected: 'Convite Recebido',
    inviteDetectedDesc: 'Foste convidado para colaborar numa história com o código:',
    validateAndJoin: 'Validar e Entrar',
    backToStory: 'Voltar à História',
    authorRankingTitle: 'Ranking de Autores',
    topAuthors: 'Os melhores do trimestre',

    ranking: 'Ranking',
    confirmDeleteSession: 'Eliminar esta sessão ativa?',
    aiEngineTitle: 'Motor de IA',
    aiEngineDesc: 'Configura o teu assistente literário.',
    provider: 'Fornecedor',
    apiKeyLabel: 'Chave de API (Secret Key)',
    getKey: 'Obter Chave',
    apiKeyLocalSecurity: 'A chave é guardada localmente no teu dispositivo e nunca é enviada para os nossos servidores.',
    saveAndContinue: 'Guardar e Continuar',
    saved: 'Guardado',
    help: 'Ajuda',
    howToGetGoogleKey: 'Como obter a chave da Google?',
    googleSteps: [
      'Acede ao Google AI Studio',
      'Inicia sessão com a tua conta Google',
      'Clica em "Get API key" no menu lateral',
      'Clica no botão "Create API key"'
    ],
    howToGetOpenAIKey: 'Como obter a chave da OpenAI?',
    openAISteps: [
      'Acede à plataforma da OpenAI',
      'Inicia sessão e adiciona saldo (é um serviço pago)',
      'Vai a "API keys" no menu lateral',
      'Clica em "Create new secret key"'
    ],
    howToGetAnthropicKey: 'Como obter a chave da Anthropic?',
    anthropicSteps: [
      'Acede à Consola da Anthropic',
      'Inicia sessão e adiciona fundos',
      'Vai a "Settings" > "API Keys"',
      'Clica em "Create Key"'
    ],
    apiKeySettings: 'Configuração da Chave API',
    apiKeyDesc: 'Se a chave de API padrão estiver congestionada ou se preferires usar a tua própria conta do Google Gemini, insere aqui a tua chave. A chave será guardada apenas localmente no teu navegador.',
    apiKeyPlaceholder: 'Insere a tua chave API Gemini (AIzaSy...)',
    apiKeySave: 'Guardar Chave',
    apiKeyClear: 'Limpar e Repor',
    apiKeyTest: 'Testar Ligação',
    apiKeyTesting: 'A testar...',
    apiKeyTestSuccess: 'Ligação bem-sucedida! O modelo Gemini 2.5-Flash está ativo.',
    apiKeyTestFail: 'Falha na ligação. Verifica se a chave é válida e se tens saldo na tua conta Google AI Studio.',
    apiKeySaved: 'Chave API guardada!',
    apiKeyCleared: 'Chave API limpa! A usar chave padrão.'
  },
  // ... other languages (en, fr) preserved or updated similarly ...
  en: {
    title: 'AI-Venture',
    tagline: 'Your Collaborative Writing Studio with Artificial Intelligence.',
    textSize: 'Text Size',
    tools: 'Tools',
    renovateCode: 'Renovate Code',
    confirmRenovate: 'Are you sure? The current code will stop working and all participants will have to rejoin with the new code.',
    codeRenovated: 'New code generated successfully!',
    nudge: 'Nudge',
    nudgeSent: 'Notification sent via email!',
    translate: 'Translate Work',
    translateDesc: (lang: string) => `Translate this work to ${lang.toUpperCase()}`,
    showOriginal: 'Show Original',
    translating: 'Translating work...',
    managePlayers: 'Manage Participants',
    kick: 'Kick',
    confirmKick: 'Are you sure you want to kick this author?',
    kickedMessage: 'You have been removed from this session by the host.',
    selectModeTitle: 'Writing Mode',
    modeSolo: 'Solo Author',
    modeSoloDesc: 'Write at your own pace with AI assistance.',
    modeCoop: 'Co-Op Group',
    modeCoopDesc: 'Create a room, invite friends, and write together.',
    modeSoloTooltip: 'Create a classic story at your own pace. The AI Editor will be by your side to help you structure the narrative.',
    modeCoopTooltip: 'Invite friends to the room. You write in synchronized turns, while the AI acts as Game Master.',
    lobbyTitle: 'Waiting Room',
    waitingForPlayers: 'Waiting for participants...',
    startGame: 'Start Setup',
    host: 'Host',
    setupWait: 'The Host is configuring the story...',
    playAsYourself: 'Roleplay as Yourself (RPG Mode)',
    playAsYourselfDesc: 'Each author receives a character sheet to fill and control.',
    assignedToYou: 'Assigned to You',
    lockedBy: 'Controlled by',
    landingTitle: 'Bring your next literary work to life.',
    landingDesc: 'The ultimate platform for modern authors. Combine your imagination with the power of AI to create, edit, and publish professional-quality literary works.',
    featuresTitle: 'What you can do in the Studio:',
    feature1Title: 'Creative Planning',
    feature1Desc: 'Define the genre, create detailed character sheets, and establish the premise with AI help.',
    feature2Title: 'Hybrid & Co-Op Writing',
    feature2Desc: 'Write alongside the AI Editor or invite friends for real-time writing sessions.',
    feature3Title: 'Professional Publishing',
    feature3Desc: 'Transform your draft into a formatted PDF book, with synopsis and automatic editorial review.',
    feature4Title: 'Global Community',
    feature4Desc: 'Read works by other authors, follow your favorites, and build your literary portfolio.',
    login: 'Login',
    signup: 'Sign Up',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    passMismatch: 'Passwords do not match.',
    username: 'Username',
    createStory: 'New Work',
    drafts: 'Drafts',
    draftsSubtitle: 'Works in progress and drafts.',
    coopWorks: 'Co-Op Works',
    coopWorksSubtitle: 'Active cooperative sessions.',
    cardCoopWorksDesc: 'Access your group writing sessions.',
    privateLibrary: 'Completed Works',
    privateLibrarySubtitle: 'Finished works ready for reading.',
    publicLibrary: 'Global Library',
    publicLibrarySubtitle: 'Works shared by the author community.',
    authorsClub: 'Authors Club',
    authorsSubtitle: 'Meet the creative minds of the platform.',
    authorsLoading: 'Loading author profiles...',
    globalLoading: 'Syncing global library...',
    profile: 'Profile',
    startAdventure: 'Start Writing',
    send: 'Send',
    sendWait: 'Waiting for turn of:',
    waitingAI: 'The Editor is writing...',
    newTurnReceived: 'New turn received from a co-author!',
    noStories: 'No finished works.',
    noDrafts: 'You have no pending drafts.',
    searchAuthor: 'Search author...',
    back: 'Back',
    next: 'Next',
    devBypass: 'Developer Mode (Bypass)',
    guestLogin: 'Login as Guest',
    guestLoginDesc: 'Continue as Guest to try all features. If you want to save your data, you will need to register an account.',
    version: `v${APP_VERSION}`,
    setupTitle: 'Work Configuration',
    setupMode: 'How do you want to start?',
    ownIdea: 'I have the Work defined',
    aiIdea: 'AI Work Suggestions',
    ideaPlaceholder: 'Describe the base idea or summary of your Work...',
    charCount: 'Number of characters',
    genreTitle: 'Literary Genre',
    qualityTitle: 'Writing Style',
    qualityRich: 'Literary (Descriptive)',
    qualityRichDesc: 'Focus on elaborate prose, introspection, and rich setting.',
    qualityDirect: 'Dynamic (Direct)',
    qualityDirectDesc: 'Focus on pacing, fluid dialogue, and rapid progression.',
    charNamesTitle: 'Character Cast',
    charNamesPlaceholder: 'Ex: Elara Vance',
    charRole: 'Narrative Function',
    charTrait: 'Psychological Profile',
    charTraitPlaceholder: 'Ex: Introverted, ambitious, melancholic...',
    charBackstory: 'Backstory',
    charBackstoryPlaceholder: 'What shaped this character before the story began?',
    charMotivations: 'Motivations',
    charMotivationsPlaceholder: 'What drives them? What is their biggest goal?',
    addCharacter: 'Add Character',
    removeCharacter: 'Remove',
    charLimit: 'Maximum of 5 characters reached.',
    roleProtagonist: 'Protagonist',
    roleAntagonist: 'Antagonist',
    roleSidekick: 'Sidekick',
    charLinksTitle: 'Group Dynamics',
    charLinksPlaceholder: 'Describe the connections, secrets, or tensions between the characters...',
    mainChar: 'Central Character',
    isMainChar: 'Narrative Focus',
    generateBook: 'Generate Book',
    polishingTitle: 'Editorial Review',
    polishingDesc: 'The Editor is reading the full work, creating the synopsis, and generating title options. This process may take up to 1 minute. Please wait...',
    synopsis: 'Editorial Synopsis',
    bookPreview: 'Work Preview',
    downloadPDF: 'Export to PDF',
    resumeStory: 'Continue Writing',
    backToHome: 'Main Dashboard',
    author: 'Author',
    date: 'Date',
    delete: 'Delete',
    resume: 'Resume',
    readBook: 'Read Work',
    confirmDelete: 'Move to archive?',
    confirmDeletePublic: 'Remove this work from the Global Library?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    publish: 'Publish',
    publishedSuccess: 'Work published successfully!',
    publishError: 'Error publishing.',
    rating: 'Rating',
    readOnly: 'Read Only',
    connectionError: 'Connection Interrupted with Editor.',
    connectionDesc: 'Could not contact the Editor.',
    online: 'Online',
    offline: 'Offline',
    authorsTitle: 'Literary Community',
    ranking: 'Author Ranking',
    works: 'Works',
    welcomeBack: 'Welcome to your Studio,',
    exploreFuncs: 'Manage your works and explore new ideas.',
    cardCreateDesc: 'Start a new work with AI support.',
    cardDraftsDesc: 'Continue working on your drafts.',
    cardLibraryPrivateDesc: 'Access your finished works.',
    cardLibraryPublicDesc: 'Read what other authors have published.',
    cardAuthorsDesc: 'View profiles of other writers.',
    cardArchiveDesc: 'Recover deleted items.',
    makeFriend: 'Follow Author',
    isFriend: 'Following',
    viewAuthorWorks: 'View Bibliography',
    privateWorks: 'Completed Works',
    publishedWorks: 'Published Works',
    authorBooksTitle: 'Author Bibliography',
    noAuthorWorks: 'This author has no published works yet.',
    close: 'Close',
    notifications: 'Notifications',
    noNotifications: 'No notifications.',
    friendNewBook: 'finished a new work:',
    markAllRead: 'Read',
    archive: 'Archive',
    archiveSubtitle: 'Deleted drafts management.',
    restore: 'Restore',
    deletePermanent: 'Delete Permanently',
    daysRemaining: 'Days',
    noArchived: 'Archive empty.',
    archiveWarning: 'Items in the archive are deleted after 30 days.',
    expiringSoon: 'Expiring soon!',
    deletePermanentlyConfirm: 'Delete permanently?',
    requestEnding: 'Close Chapter',
    endingPrompt: 'Write the outcome of this arc or chapter in a literary way.',
    requestDefinitiveEnding: 'Definitive Ending',
    definitiveEndingPrompt: 'Create an absolute conclusion for this work. Resolve all conflicts, offer a satisfying emotional outcome, and end the story definitively, without hooks or pending mysteries.',
    endingActive: 'Finalization Active',
    introGenerating: 'The Editor is writing the introduction...',
    endingLockedReason: (needed: number) => `The narrative still requires more development (Minimum ${needed} paragraphs).`,
    aiSystemRole: 'You act as an elite "AI Literary Editor" in English. GOLDEN RULES: 1. NEVER respond to conversations, apologies, or user phrases. Your output must be 100% NARRATIVE. 2. If the user gives an instruction (e.g., "continue", "fix"), execute it silently in the text without saying "Ok" or "Here is". 3. Each character speech must be in a new paragraph with a dash (—). 4. Avoid meta-comments.',
    aiInitialPrompt: (idea: string, style: string, genre: string, chars: string, leader: string, links: string) => `Greetings, Author. We begin writing this work of ${genre}. CONCEPT: ${idea}. CAST: ${chars}. RELATIONS: ${links}. Write the first chapter focusing on immersion and character introduction.`,
    tutorialTitle: 'Author Manual',
    tutorialStep1: 'New Work',
    tutorialStep1Desc: 'Start a new literary adventure. You can create your story solo or invite friends for Co-Op Mode.',
    tutorialStep2: 'Drafts',
    tutorialStep2Desc: 'Access your works in progress. Never lose the plot and resume writing exactly where you left off.',
    tutorialStep3: 'Completed Works',
    tutorialStep3Desc: 'Your personal bookshelf with all finished works. Export to PDF, translate, or publish them.',
    tutorialStep4: 'Global Library',
    tutorialStep4Desc: 'Explore the vast universe of works published by other authors. Read, rate, and get inspired.',
    tutorialStep5: 'Authors Club',
    tutorialStep5Desc: 'Meet the creative minds of the platform. Follow your favorite authors and track their releases.',
    tutorialStep6: 'Archive',
    tutorialStep6Desc: 'Access works and drafts you deleted. You can restore them if you change your mind (items kept for 30 days).',
    coopModalTitle: 'How does Co-Op Mode work?',
    coopStep1: 'Lobby & Invites',
    coopStep1Desc: 'Create a Lobby and share the code or link with friends. The host controls who enters (and who leaves).',
    coopStep2: 'Collaborative Setup',
    coopStep2Desc: 'Everyone sees the characters. The Host defines the story, but everyone can create their own hero in RPG mode.',
    coopStep3: 'Real-Time Sync',
    coopStep3Desc: 'Write in turns. The "lock" indicates whose turn it is. The AI maintains cohesion between all authors.',
    coopStep4: 'Modes & Roles',
    coopStep4Desc: 'In "Classic" mode, everyone controls everything. In "RPG (Roleplay as Yourself)" mode, each author controls only their character.',
    genres: {
      fantasy: 'Fantasy',
      high_fantasy: 'High Fantasy',
      urban_fantasy: 'Urban Fantasy',
      scifi: 'Science Fiction',
      hard_scifi: 'Hard Sci-Fi',
      space_opera: 'Space Opera',
      hist_romance: 'Historical Romance',
      regency: 'Regency Romance',
      thriller: 'Thriller',
      crime: 'Crime Fiction',
      horror: 'Horror',
      psych_horror: 'Psychological Horror',
      mystery: 'Mystery',
      noir: 'Noir',
      drama: 'Drama',
      dystopia: 'Dystopia',
      adventure: 'Adventure',
      western: 'Western',
      romcom: 'Contemporary Romance',
      cyberpunk: 'Cyberpunk',
      steampunk: 'Steampunk',
      magical_realism: 'Magical Realism',
      fairy_tale: 'Fairy Tale',
      satire: 'Satire',
      spy: 'Espionage',
      mythology: 'Mythology',
      biography: 'Fictional Biography',
      comedy: 'Comedy',
      tragedy: 'Tragedy',
      slice_of_life: 'Slice of Life',
      litrpg: 'LitRPG / Isekai',
      superhero: 'Superheroes',
      surprise: 'Surprise 🎉'
    },
    tutorialIntro: 'Welcome to AI-Venture, your assisted writing studio.',
    tutorialBtn: 'Understood',
    authError: 'Access error.',
    loginSuccess: 'Welcome to the Studio!',
    signupSuccess: 'Check your email to confirm the account.',
    fallbackSuggestion1: 'Develop dialogue.',
    fallbackSuggestion2: 'Describe environment.',
    fallbackSuggestion3: 'Explore thought.',
    joinSession: 'Join Co-Op Mode',
    joinSessionDesc: 'Enter the code for collaboration.',
    enterCode: 'Session Code',
    join: 'Join',
    sessionError: 'Session not found.',
    liveSync: 'Neural Sync',
    inviteCode: 'Invite Code',
    help: 'Help',
    copy: 'Copy',
    startLiveSession: 'Cooperative Mode',
    liveSessionActive: 'CO-OP',
    shareWithCoAuthor: 'Share this code with your co-author:',
    syncing: 'Syncing (Co-Author Turn)...',
    publishToGlobal: 'Publish to Library',
    publishing: 'Analyzing Narrative...',
    alreadyPublished: 'Already published',
    acclaim: 'Acclaim',
    votes: 'Acclaims',
    removePublic: 'Privatize',
    confirmRemovePublic: 'Are you sure you want to remove this work from the Global Library?',
    removedSuccess: 'Work removed from public library.',
    successTitle: 'Success!',
    goToLogin: 'Go to Login',
    generatingConcepts: 'Generating Work concepts...',
    tryAgain: 'Try again',
    stepCounter: (c: number, t: number) => `Step ${c} of ${t}`,
    noName: 'No Name',
    guestCoopLock: 'Register to unlock Cooperative Mode and write with friends.',
    whatsNew: 'What\'s New',
    changelogTitle: 'Update Log',
    newUpdate: 'New Version!',
    activeSession: 'Active Session',
    backToLobby: 'Back to Lobby',
    reopenBook: 'Reopen for Editing',
    reopenWarn: 'The work will return to drafts.',
    howItWorks: 'How it works?',
    labelName: 'Name',
    labelRole: 'Role',
    labelTraits: 'Traits & Personality',
    turnYourTurn: 'It\'s your turn to write!',
    turnLocked: 'Spectator Mode',
    turnParticipants: 'Authors in Session',
    titleSelection: 'Define Work Title',
    selectTitleDesc: 'The Editor suggested 3 titles for your work. Choose one or write your own.',
    customTitlePlaceholder: 'Write your custom title...',
    orCustom: 'Or create your original title',
    inviteFriend: 'Invite Friend',
    inviteDesc: 'Share the link or send an email to bring a co-author to this story.',
    copyLink: 'Copy Link',
    linkCopied: 'Link Copied!',
    sendEmail: 'Send Email',
    shareLink: 'Share Link',
    inviteSubject: 'Invitation to write on AI-Venture',
    inviteBody: (code: string, link: string) => `Hello! Join me to write a story on AI-Venture.\n\nSession Code: ${code}\n\nOr click directly here: ${link}`,
    inviteDetected: 'Invitation Received',
    inviteDetectedDesc: 'You were invited to collaborate on a story with the code:',
    validateAndJoin: 'Validate and Join',
    backToStory: 'Back to Story',
    aiEngineTitle: 'AI Engine',
    aiEngineDesc: 'Configure your literary assistant.',
    provider: 'Provider',
    apiKeyLabel: 'API Key (Secret Key)',
    getKey: 'Get Key',
    apiKeyLocalSecurity: 'The key is stored locally on your device and is never sent to our servers.',
    saveAndContinue: 'Save and Continue',
    saved: 'Saved',
    help: 'Help',
    howToGetGoogleKey: 'How to get the Google key?',
    googleSteps: [
      'Go to Google AI Studio',
      'Log in with your Google account',
      'Click on "Get API key" in the side menu',
      'Click the "Create API key" button'
    ],
    howToGetOpenAIKey: 'How to get the OpenAI key?',
    openAISteps: [
      'Go to the OpenAI platform',
      'Log in and add balance (it is a paid service)',
      'Go to "API keys" in the side menu',
      'Click on "Create new secret key"'
    ],
    howToGetAnthropicKey: 'How to get the Anthropic key?',
    anthropicSteps: [
      'Go to the Anthropic Console',
      'Log in and add funds',
      'Go to "Settings" > "API Keys"',
      'Click on "Create Key"'
    ],
    apiKeySettings: 'API Key Configuration',
    apiKeyDesc: 'If the default API key is congested or if you prefer to use your own Google Gemini account, enter your key here. The key will be stored only locally in your browser.',
    apiKeyPlaceholder: 'Enter your Gemini API key (AIzaSy...)',
    apiKeySave: 'Save Key',
    apiKeyClear: 'Clear and Reset',
    apiKeyTest: 'Test Connection',
    apiKeyTesting: 'Testing...',
    apiKeyTestSuccess: 'Connection successful! The Gemini 2.5-Flash model is active.',
    apiKeyTestFail: 'Connection failed. Verify if the key is valid and if you have credits in your Google AI Studio account.',
    apiKeySaved: 'API Key saved!',
    apiKeyCleared: 'API Key cleared! Using default key.'
  },
  fr: {
    title: 'AI-Venture',
    tagline: 'Votre Studio d\'Écriture Collaborative avec Intelligence Artificielle.',
    textSize: 'Taille du Texte',
    tools: 'Outils',
    renovateCode: 'Renouveler le Code',
    confirmRenovate: 'Êtes-vous sûr ? Le code actuel cessera de fonctionner et tous les participants devront rejoindre avec le nouveau code.',
    codeRenovated: 'Nouveau code généré avec succès !',
    nudge: 'Rappel',
    nudgeSent: 'Notification envoyée par e-mail !',
    translate: 'Traduire l\'Œuvre',
    translateDesc: (lang: string) => `Traduire cette œuvre en ${lang.toUpperCase()}`,
    showOriginal: 'Voir l\'Original',
    translating: 'Traduction de l\'œuvre...',
    managePlayers: 'Gérer les Participants',
    kick: 'Expulser',
    confirmKick: 'Êtes-vous sûr de vouloir expulser cet auteur ?',
    kickedMessage: 'Vous avez été retiré de cette session par l\'hôte.',
    selectModeTitle: 'Mode d\'Écriture',
    modeSolo: 'Auteur Solo',
    modeSoloDesc: 'Écrivez à votre rythme avec l\'aide de l\'IA.',
    modeCoop: 'Groupe Co-Op',
    modeCoopDesc: 'Créez une salle, invitez des amis et écrivez ensemble.',
    modeSoloTooltip: 'Créez une œuvre classique à votre propre rythme. L\'Éditeur IA sera à vos côtés pour vous aider à structurer le récit.',
    modeCoopTooltip: 'Invitez des amis dans la salle. Vous écrivez en tours synchronisés, pendant que l\'IA joue le rôle de Maître de Jeu.',
    lobbyTitle: 'Salle d\'Attente',
    waitingForPlayers: 'En attente de participants...',
    startGame: 'Commencer la Configuration',
    host: 'Hôte',
    setupWait: 'L\'Hôte configure l\'histoire...',
    playAsYourself: 'Jouer son Propre Rôle (Mode RPG)',
    playAsYourselfDesc: 'Chaque auteur reçoit une fiche de personnage à remplir et contrôler.',
    assignedToYou: 'Attribué à Vous',
    lockedBy: 'Contrôlé par',
    landingTitle: 'Donnez vie à votre prochaine œuvre littéraire.',
    landingDesc: 'La plateforme ultime pour les auteurs modernes. Combinez votre imagination avec la puissance de l\'IA pour créer, éditer et publier des œuvres littéraires de qualité professionnelle.',
    featuresTitle: 'Ce que vous pouvez faire dans le Studio :',
    feature1Title: 'Planification Créative',
    feature1Desc: 'Définissez le genre, créez des fiches de personnages détaillées et établissez la prémisse avec l\'aide de l\'IA.',
    feature2Title: 'Écriture Hybride & Co-Op',
    feature2Desc: 'Écrivez aux côtés de l\'Éditeur IA ou invitez des amis pour des sessions d\'écriture en temps réel.',
    feature3Title: 'Publication Professionnelle',
    feature3Desc: 'Transformez votre brouillon en un livre PDF formaté, avec synopsis et révision éditoriale automatique.',
    feature4Title: 'Communauté Mondiale',
    feature4Desc: 'Lisez des œuvres d\'autres auteurs, suivez vos favoris et construisez votre portefeuille littéraire.',
    login: 'Connexion',
    signup: 'S\'inscrire',
    noAccount: 'Pas encore de compte ?',
    haveAccount: 'Déjà un compte ?',
    logout: 'Déconnexion',
    email: 'E-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le Mot de passe',
    passMismatch: 'Les mots de passe ne correspondent pas.',
    username: 'Nom d\'utilisateur',
    createStory: 'Nouvelle Œuvre',
    drafts: 'Brouillons',
    draftsSubtitle: 'Travaux en cours et brouillons.',
    coopWorks: 'Œuvres Co-Op',
    coopWorksSubtitle: 'Sessions coopératives actives.',
    cardCoopWorksDesc: 'Accédez à vos sessions d\'écriture en groupe.',
    privateLibrary: 'Œuvres Terminées',
    privateLibrarySubtitle: 'Œuvres finalisées prêtes à la lecture.',
    publicLibrary: 'Bibliothèque Mondiale',
    publicLibrarySubtitle: 'Œuvres partagées par la communauté d\'auteurs.',
    authorsClub: 'Club des Auteurs',
    authorsSubtitle: 'Rencontrez les esprits créatifs de la plateforme.',
    authorsLoading: 'Chargement des profils d\'auteurs...',
    globalLoading: 'Synchronisation de la bibliothèque mondiale...',
    profile: 'Profil',
    startAdventure: 'Commencer à Écrire',
    send: 'Envoyer',
    sendWait: 'En attente du tour de :',
    waitingAI: 'L\'Éditeur écrit...',
    newTurnReceived: 'Nouveau tour reçu d\'un co-auteur !',
    noStories: 'Aucune œuvre terminée.',
    noDrafts: 'Vous n\'avez aucun brouillon en attente.',
    searchAuthor: 'Rechercher un auteur...',
    back: 'Retour',
    next: 'Suivant',
    devBypass: 'Mode Développeur (Bypass)',
    guestLogin: 'Connexion Invité',
    guestLoginDesc: 'Continuez en tant qu\'invité pour essayer toutes les fonctionnalités. Si vous souhaitez sauvegarder vos données, vous devrez créer un compte.',
    version: `v${APP_VERSION}`,
    setupTitle: 'Configuration de l\'Œuvre',
    setupMode: 'Comment souhaitez-vous commencer ?',
    ownIdea: 'J\'ai l\'Œuvre définie',
    aiIdea: 'Suggestions d\'Œuvre par l\'IA',
    ideaPlaceholder: 'Décrivez l\'idée de base ou le résumé de votre Œuvre...',
    charCount: 'Nombre de personnages',
    genreTitle: 'Genre Littéraire',
    qualityTitle: 'Style d\'Écriture',
    qualityRich: 'Littéraire (Descriptif)',
    qualityRichDesc: 'Focus sur la prose élaborée, l\'introspection et une ambiance riche.',
    qualityDirect: 'Dynamique (Direct)',
    qualityDirectDesc: 'Focus sur le rythme, les dialogues fluides et une progression rapide.',
    charNamesTitle: 'Casting des Personnages',
    charNamesPlaceholder: 'Ex : Elara Vance',
    charRole: 'Fonction Narrative',
    charTrait: 'Profil Psychologique',
    charTraitPlaceholder: 'Ex : Introverti, ambitieux, mélancolique...',
    charBackstory: 'Histoire Antérieure',
    charBackstoryPlaceholder: 'Qu\'est-ce qui a façonné ce personnage avant le début de l\'histoire ?',
    charMotivations: 'Motivations',
    charMotivationsPlaceholder: 'Qu\'est-ce qui le motive ? Quel est son plus grand objectif ?',
    addCharacter: 'Ajouter Personnage',
    removeCharacter: 'Supprimer',
    charLimit: 'Maximum de 5 personnages atteint.',
    roleProtagonist: 'Protagoniste',
    roleAntagonist: 'Antagoniste',
    roleSidekick: 'Secondaire',
    charLinksTitle: 'Dynamique de Groupe',
    charLinksPlaceholder: 'Décrivez les liens, secrets ou tensions entre les personnages...',
    mainChar: 'Personnage Central',
    isMainChar: 'Focus Narratif',
    generateBook: 'Générer le Livre',
    polishingTitle: 'Révision Éditoriale',
    polishingDesc: 'L\'Éditeur lit l\'œuvre complète, crée le synopsis et génère des options de titres. Ce processus peut prendre jusqu\'à 1 minute. Veuillez patienter...',
    synopsis: 'Synopsis Éditorial',
    bookPreview: 'Aperçu de l\'Œuvre',
    downloadPDF: 'Exporter en PDF',
    resumeStory: 'Continuer l\'Écriture',
    backToHome: 'Tableau de Bord Principal',
    author: 'Auteur',
    date: 'Date',
    delete: 'Supprimer',
    resume: 'Reprendre',
    readBook: 'Lire l\'Œuvre',
    confirmDelete: 'Déplacer vers les archives ?',
    confirmDeletePublic: 'Retirer cette œuvre de la Bibliothèque Mondiale ?',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    publish: 'Publier',
    publishedSuccess: 'Œuvre publiée avec succès !',
    publishError: 'Erreur lors de la publication.',
    rating: 'Évaluation',
    readOnly: 'Lecture Seule',
    connectionError: 'Connexion Interrompue avec l\'Éditeur.',
    connectionDesc: 'Impossible de contacter l\'Éditeur.',
    online: 'En ligne',
    offline: 'Hors ligne',
    authorsTitle: 'Communauté Littéraire',
    works: 'Œuvres',
    welcomeBack: 'Bienvenue dans votre Studio,',
    exploreFuncs: 'Gérez vos œuvres et explorez de nouvelles idées.',
    cardCreateDesc: 'Commencez une nouvelle œuvre avec le soutien de l\'IA.',
    cardDraftsDesc: 'Continuez à travailler sur vos brouillons.',
    cardLibraryPrivateDesc: 'Accédez à vos œuvres terminées.',
    cardLibraryPublicDesc: 'Lisez ce que d\'autres auteurs ont publié.',
    cardAuthorsDesc: 'Voir le profil d\'autres écrivains.',
    cardArchiveDesc: 'Récupérez les éléments supprimés.',
    makeFriend: 'Suivre l\'Auteur',
    isFriend: 'Suivi',
    viewAuthorWorks: 'Voir la Bibliographie',
    privateWorks: 'Œuvres Terminées',
    publishedWorks: 'Œuvres Publiées',
    authorBooksTitle: 'Bibliographie de l\'Auteur',
    noAuthorWorks: 'Cet auteur n\'a pas encore d\'œuvres publiées.',
    close: 'Fermer',
    notifications: 'Notifications',
    noNotifications: 'Aucune notification.',
    friendNewBook: 'a terminé une nouvelle œuvre :',
    markAllRead: 'Lues',
    archive: 'Archives',
    archiveSubtitle: 'Gestion des brouillons supprimés.',
    restore: 'Restaurer',
    deletePermanent: 'Supprimer Définitivement',
    daysRemaining: 'Jours',
    noArchived: 'Archives vides.',
    archiveWarning: 'Les éléments dans les archives sont supprimés après 30 jours.',
    expiringSoon: 'Expire bientôt !',
    deletePermanentlyConfirm: 'Supprimer définitivement ?',
    requestEnding: 'Fermer le Chapitre',
    endingPrompt: 'Écrivez le dénouement de cet arc ou chapitre de manière littéraire.',
    requestDefinitiveEnding: 'Fin Définitive',
    definitiveEndingPrompt: 'Créez une conclusion absolue pour cette œuvre. Résolvez tous les conflits, offrez un dénouement émotionnel satisfaisant et terminez l\'histoire de manière définitive, sans accroches ou mystères en suspens.',
    endingActive: 'Finalisation Active',
    introGenerating: 'L\'Éditeur rédige l\'introduction...',
    endingLockedReason: (needed: number) => `Le récit nécessite encore plus de développement (Minimum ${needed} paragraphes).`,
    aiSystemRole: 'Vous agissez en tant qu\'"Éditeur Littéraire IA" d\'élite en Français. RÈGLES D\'OR : 1. NE JAMAIS répondre aux conversations, excuses ou phrases de l\'utilisateur. Votre sortie doit être 100% NARRATIVE. 2. Si l\'utilisateur donne une instruction (ex : "continue", "corrige"), exécutez-la silencieusement dans le texte sans dire "Ok" ou "Voici". 3. Chaque parole de personnage doit être dans un nouveau paragraphe avec un tiret (—). 4. Évitez les méta-commentaires.',
    aiInitialPrompt: (idea: string, style: string, genre: string, chars: string, leader: string, links: string) => `Salutations, Auteur. Nous commençons la rédaction de cette œuvre de ${genre}. CONCEPT : ${idea}. CASTING : ${chars}. RELATIONS : ${links}. Rédigez le premier chapitre en vous concentrant sur l'immersion et l'introduction des personnages.`,
    tutorialTitle: 'Manuel de l\'Auteur',
    tutorialStep1: 'Nouvelle Œuvre',
    tutorialStep1Desc: 'Commencez une nouvelle aventure littéraire. Vous pouvez créer votre histoire en solo ou inviter des amis en Mode Co-Op.',
    tutorialStep2: 'Brouillons',
    tutorialStep2Desc: 'Accédez à vos œuvres en cours. Ne perdez jamais le fil et reprenez l\'écriture exactement où vous vous étiez arrêté.',
    tutorialStep3: 'Œuvres Terminées',
    tutorialStep3Desc: 'Votre étagère personnelle avec toutes vos œuvres terminées. Exportez-les en PDF, traduisez-les ou publiez-les.',
    tutorialStep4: 'Bibliothèque Mondiale',
    tutorialStep4Desc: 'Explorez le vaste univers des œuvres publiées par d\'autres auteurs. Lisez, évaluez et laissez-vous inspirer.',
    tutorialStep5: 'Club des Auteurs',
    tutorialStep5Desc: 'Rencontrez les esprits créatifs de la plateforme. Suivez vos auteurs préférés et surveillez leurs nouveautés.',
    tutorialStep6: 'Archives',
    tutorialStep6Desc: 'Accédez aux œuvres et brouillons que vous avez supprimés. Vous pouvez les restaurer si vous changez d\'avis (éléments conservés 30 jours).',
    coopModalTitle: 'Comment fonctionne le Mode Co-Op ?',
    coopStep1: 'Lobby & Invitations',
    coopStep1Desc: 'Créez un Lobby et partagez le code ou le lien avec des amis. L\'hôte contrôle qui entre (et qui sort).',
    coopStep2: 'Configuration Collaborative',
    coopStep2Desc: 'Tout le monde voit les personnages. L\'Hôte définit l\'histoire, mais chacun peut créer son propre héros en mode RPG.',
    coopStep3: 'Synchro Temps Réel',
    coopStep3Desc: 'Écrivez à tour de rôle. Le "cadenas" indique à qui est le tour. L\'IA maintient la cohésion entre tous les auteurs.',
    coopStep4: 'Modes & Rôles',
    coopStep4Desc: 'En mode "Classique", tout le monde contrôle tout. En mode "RPG (Jouer son Propre Rôle)", chaque auteur ne contrôle que son personnage.',
    genres: {
      fantasy: 'Fantaisie',
      high_fantasy: 'High Fantasy',
      urban_fantasy: 'Urban Fantasy',
      scifi: 'Science-Fiction',
      hard_scifi: 'Hard Sci-Fi',
      space_opera: 'Space Opera',
      hist_romance: 'Romance Historique',
      regency: 'Romance d\'Époque',
      thriller: 'Thriller',
      crime: 'Policier / Crime',
      horror: 'Horreur',
      psych_horror: 'Horreur Psychologique',
      mystery: 'Mystère',
      noir: 'Noir',
      drama: 'Drame',
      dystopia: 'Dystopie',
      adventure: 'Aventure',
      western: 'Western',
      romcom: 'Romance Contemporaine',
      cyberpunk: 'Cyberpunk',
      steampunk: 'Steampunk',
      magical_realism: 'Réalisme Magique',
      fairy_tale: 'Conte de Fées',
      satire: 'Satire',
      spy: 'Espionnage',
      mythology: 'Mythologie',
      biography: 'Biographie Fictive',
      comedy: 'Comédie',
      tragedy: 'Tragédie',
      slice_of_life: 'Tranche de vie',
      litrpg: 'LitRPG / Isekai',
      superhero: 'Super-héros',
      surprise: 'Surprise 🎉'
    },
    tutorialIntro: 'Bienvenue sur AI-Venture, votre studio de rédaction assistée.',
    tutorialBtn: 'Compris',
    authError: 'Erreur d\'accès.',
    loginSuccess: 'Bienvenue dans le Studio !',
    signupSuccess: 'Vérifiez votre e-mail pour confirmer le compte.',
    fallbackSuggestion1: 'Développer le dialogue.',
    fallbackSuggestion2: 'Décrire l\'environnement.',
    fallbackSuggestion3: 'Explorer la pensée.',
    joinSession: 'Rejoindre le Mode Co-Op',
    joinSessionDesc: 'Entrez le code pour la collaboration.',
    enterCode: 'Code de Session',
    join: 'Rejoindre',
    sessionError: 'Session introuvable.',
    liveSync: 'Synchro Neurale',
    inviteCode: 'Code d\'Invitation',
    help: 'Aide',
    copy: 'Copier',
    startLiveSession: 'Mode Coopératif',
    liveSessionActive: 'CO-OP',
    shareWithCoAuthor: 'Partagez ce code avec votre co-auteur :',
    syncing: 'Synchronisation (Tour du Co-Auteur)...',
    publishToGlobal: 'Publier dans la Bibliothèque',
    publishing: 'Analyse Narrative...',
    alreadyPublished: 'Déjà publiée',
    acclaim: 'Acclamer',
    votes: 'Acclamations',
    removePublic: 'Privatiser',
    confirmRemovePublic: 'Êtes-vous sûr de vouloir retirer cette œuvre de la Bibliothèque Mondiale ?',
    removedSuccess: 'Œuvre retirée de la bibliothèque publique.',
    successTitle: 'Succès !',
    goToLogin: 'Aller à la Connexion',
    generatingConcepts: 'Génération des concepts de l\'Œuvre...',
    tryAgain: 'Réessayer',
    stepCounter: (c: number, t: number) => `Étape ${c} sur ${t}`,
    noName: 'Sans Nom',
    guestCoopLock: 'Inscrivez-vous pour débloquer le Mode Coopératif et écrire avec des amis.',
    whatsNew: 'Nouveautés',
    changelogTitle: 'Journal des Mises à Jour',
    newUpdate: 'Nouvelle Version !',
    activeSession: 'Session Active',
    backToLobby: 'Retour au Lobby',
    reopenBook: 'Rouvrir pour Édition',
    reopenWarn: 'L\'œuvre retournera dans les brouillons.',
    howItWorks: 'Comment ça marche ?',
    labelName: 'Nom',
    labelRole: 'Rôle',
    labelTraits: 'Traits & Personnalité',
    turnYourTurn: 'C\'est à votre tour d\'écrire !',
    turnLocked: 'Mode Spectateur',
    turnParticipants: 'Auteurs dans la Session',
    titleSelection: 'Définir le Titre de l\'Œuvre',
    selectTitleDesc: 'L\'Éditeur a suggéré 3 titres pour votre œuvre. Choisissez-en un ou écrivez le vôtre.',
    customTitlePlaceholder: 'Écrivez votre titre personnalisé...',
    orCustom: 'Ou créez votre titre original',
    inviteFriend: 'Inviter un Ami',
    inviteDesc: 'Partagez le lien ou envoyez un e-mail pour amener un co-auteur dans cette histoire.',
    copyLink: 'Copier le Lien',
    linkCopied: 'Lien Copié !',
    sendEmail: 'Envoyer E-mail',
    shareLink: 'Partager le Lien',
    inviteSubject: 'Invitation à écrire sur AI-Venture',
    inviteBody: (code: string, link: string) => `Bonjour ! Rejoignez-moi pour écrire une histoire sur AI-Venture.\n\nCode de Session : ${code}\n\nOu cliquez directement ici : ${link}`,
    inviteDetected: 'Invitation Reçue',
    inviteDetectedDesc: 'Vous avez été invité à collaborer sur une histoire avec le code :',
    validateAndJoin: 'Valider et Entrer',
    backToStory: 'Retour à l\'Histoire',
    authorRankingTitle: 'Classement des Auteurs',
    topAuthors: 'Les meilleurs du trimestre',

    ranking: 'Classement',
    confirmDeleteSession: 'Supprimer cette session active ?',
    aiEngineTitle: 'Moteur d\'IA',
    aiEngineDesc: 'Configurez votre assistant littéraire.',
    provider: 'Fournisseur',
    apiKeyLabel: 'Clé API (Clé Secrète)',
    getKey: 'Obtenir la clé',
    apiKeyLocalSecurity: 'La clé est stockée localement sur votre appareil et n\'est jamais envoyée à nos serveurs.',
    saveAndContinue: 'Enregistrer et continuer',
    saved: 'Enregistré',
    help: 'Aide',
    howToGetGoogleKey: 'Comment obtenir la clé Google ?',
    googleSteps: [
      'Accédez à Google AI Studio',
      'Connectez-vous avec votre compte Google',
      'Cliquez sur "Get API key" dans le menu latéral',
      'Cliquez sur le bouton "Create API key"'
    ],
    howToGetOpenAIKey: 'Comment obtenir la clé OpenAI ?',
    openAISteps: [
      'Accédez à la plateforme OpenAI',
      'Connectez-vous et ajoutez un solde (c\'est un service payant)',
      'Allez dans "API keys" dans le menu latéral',
      'Cliquez sur "Create new secret key"'
    ],
    howToGetAnthropicKey: 'Comment obtenir la clé Anthropic ?',
    anthropicSteps: [
      'Accédez à la Console Anthropic',
      'Connectez-vous et ajoutez des fonds',
      'Allez dans "Settings" > "API Keys"',
      'Cliquez sur "Create Key"'
    ],
    apiKeySettings: 'Configuration de la Clé API',
    apiKeyDesc: 'Si la clé API par défaut est saturée ou si vous préférez utiliser votre propre compte Google Gemini, saisissez votre clé ici. La clé sera stockée uniquement localement dans votre navigateur.',
    apiKeyPlaceholder: 'Saisissez votre clé API Gemini (AIzaSy...)',
    apiKeySave: 'Enregistrer la Clé',
    apiKeyClear: 'Effacer et Réinitialiser',
    apiKeyTest: 'Tester la Connexion',
    apiKeyTesting: 'Test en cours...',
    apiKeyTestSuccess: 'Connexion réussie ! Le modèle Gemini 2.5-Flash est actif.',
    apiKeyTestFail: 'Échec de la connexion. Vérifiez si la clé est valide et si vous avez des crédits sur votre compte Google AI Studio.',
    apiKeySaved: 'Clé API enregistrée !',
    apiKeyCleared: 'Clé API effacée ! Utilisation de la clé par défaut.'
  }
};